# Generated by Django 3.2.9 on 2022-02-03 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('creation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_time', models.DateTimeField()),
            ],
        ),
    ]
